class OttPlatform4Executor{

	
 static String englishSeries[] = {"The Shawshank Redemption", "The Godfather", "The Dark Knight", "The Godfather Part", "Angry Men", "Schindlers List", "The Return of the King", "Pulp Fiction", "Forrest Gump", "Goodfellas", "The Matrix", "The Kitchen", "One life", "Dark Desires", "One Day", "Conjuring", "Oppenheimer", "Barbie", "Spirited Away", "The painist", "Whiplash", "Rear Window", "Alien", "Apocalypse Now", "City Lights"};
 static String hindiSeries[] = {"Schindlers List", "The Return of the King", "Pulp Fiction", "Forrest Gump", "Goodfellas", "The Matrix", "The Kitchen", "One life", "Dark Desires", "One Day", "Conjuring", "Oppenheimer", "Barbie", "Spirited Away", "The painist", "Whiplash", "Rear Window", "Alien", "Apocalypse Now", "City Lights"};
 static String kanndaSeries[] = {"KGF", "Pailwan", "Robert", "Toby", "Navrasa", "The Shawshank Redemption", "The Godfather", "The Dark Knight", "The Godfather Part", "Angry Men", "Schindlers List", "The Return of the King", "Pulp Fiction", "Forrest Gump", "Goodfellas", "The Matrix", "The Kitchen", "One life", "Dark Desires", "One Day", "Conjuring", "Oppenheimer", "Barbie", "Spirited Away", "The painist", "Whiplash", "Rear Window", "Alien", "Apocalypse Now", "City Lights"};
 static String telguSeries[] = {"The Shawshank Redemption", "The Godfather", "The Dark Knight", "The Godfather Part", "Angry Men", "Schindlers List", "The Return of the King", "Pulp Fiction", "Forrest Gump", "Goodfellas", "The Matrix", "The Kitchen", "One life", "Dark Desires", "One Day", "Conjuring", "Oppenheimer", "Barbie", "Spirited Away", "The painist", "Whiplash", "Rear Window", "Alien", "Apocalypse Now", "City Lights",};
 static String tamilSeries[] = {"Schindlers List", "The Return of the King", "Pulp Fiction", "Forrest Gump", "Goodfellas", "The Matrix", "The Kitchen", "One life", "Dark Desires", "One Day", "Conjuring", "Oppenheimer", "Barbie", "Spirited Away", "The painist", "Whiplash", "Rear Window", "Alien", "Apocalypse Now", "City Lights",};
   public static void main(String prime[]){
  Prime movies = new  Prime();
   movies.movies("The englishSeries of OttPlatform4 are " + englishSeries[0] + englishSeries[1] + englishSeries[2] + englishSeries[3] + englishSeries[4] + englishSeries[5] + englishSeries[6] + englishSeries[7] + englishSeries[8] + englishSeries[9] + englishSeries[10] + englishSeries[11] + englishSeries[12] + englishSeries[13] + englishSeries[14] + englishSeries[16] + englishSeries[17] + englishSeries[18] + englishSeries[19] + englishSeries[20]);
   movies.movies("The hindiSeries of OttPlatform4 are " + hindiSeries[1] + hindiSeries[2] + hindiSeries[3] + hindiSeries[4] + hindiSeries[5] + hindiSeries[6] + hindiSeries[7] + hindiSeries[8] + hindiSeries[9] + hindiSeries[10] + hindiSeries[11] + hindiSeries[12] + hindiSeries[13] + hindiSeries[14] + hindiSeries[15]);
   movies.movies("The kanndaSeries of OttPlatform4 are " + kanndaSeries[1] + kanndaSeries[2] + kanndaSeries[3] + kanndaSeries[4] + kanndaSeries[5] + kanndaSeries[6] + kanndaSeries[7] + kanndaSeries[8] + kanndaSeries[9] + kanndaSeries[10] + kanndaSeries[11] + kanndaSeries[12] + kanndaSeries[13] + kanndaSeries[14] + kanndaSeries[15] + kanndaSeries[16] + kanndaSeries[17] + kanndaSeries[18] + kanndaSeries[19] + kanndaSeries[20] + kanndaSeries[21] + kanndaSeries[22] + kanndaSeries[23] + kanndaSeries[24] + kanndaSeries[25]);
   movies.movies("The telguSeries of OttPlatform4 are " + telguSeries[1] + telguSeries[2] + telguSeries[3] + telguSeries[4] + telguSeries[5] + telguSeries[6] + telguSeries[7] + telguSeries[8] + telguSeries[9] + telguSeries[10] + telguSeries[11] + telguSeries[12] + telguSeries[13] + telguSeries[14] + telguSeries[15] + telguSeries[16] + telguSeries[17] + telguSeries[18] + telguSeries[19] + telguSeries[20] + telguSeries[21] + telguSeries[22] + telguSeries[23] + telguSeries[24] + telguSeries[25] );
   movies.movies("The tamilSeries of OttPlatform4 are " +tamilSeries[1] + tamilSeries[2] + tamilSeries[3] + tamilSeries[4] + tamilSeries[5] + tamilSeries[6] + tamilSeries[7] + tamilSeries[8] + tamilSeries[9] + tamilSeries[10] + tamilSeries[11] + tamilSeries[12] + tamilSeries[13] + tamilSeries[14] + tamilSeries[15] + tamilSeries[16] + tamilSeries[17] + tamilSeries[18] + tamilSeries[19] + tamilSeries[20]);
   
	}
	}